name: 'Create Pull Request'

on:
  push:
    branches:
      - 'feature/**' # Aciona o workflow em qualquer branch que comece com "feature/"

permissions:
  pull-requests: write # Permite criar e gerenciar PRs  
  contents: read


jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      # Este passo usa a CLI oficial do GitHub para criar o PR.
      # É a forma mais robusta e correta de realizar esta automação.
      - name: Create Pull Request if it does not exist
        env:
          # O GITHUB_TOKEN com as permissões definidas acima é passado para a CLI.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          # Primeiro, verificamos se já existe um PR aberto para esta branch para evitar erros.
          existing_pr=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')
          
          if [ -z "$existing_pr" ]; then
            echo "Nenhum PR encontrado para a branch $BRANCH_NAME. Criando um novo PR."
            gh pr create \
              --base main \
              --head "$BRANCH_NAME" \
              --title "feat: PR da branch ${{ github.ref_name }}" \
              --body "Este PR foi criado automaticamente. Por favor, revise as alterações." \
              --label "automacao,para-revisao"
          else
            echo "Um PR (#$existing_pr) já existe para a branch $BRANCH_NAME. Nada a fazer."
          fi