name: 'Deploy EKS Cluster with Terraform'

on:
  push:
    branches:
      - main # Roda o apply quando houver push na main
  pull_request: # Roda apenas o plan para pull requests


permissions:
  id-token: write # Permissão para o workflow obter um OIDC token
  pull-requests: write # Permissão para comentar nos Pull Requests
  contents: read  # Permissão para o workflow ler o repositório
  statuses: write # Permissão para criar status checks

# Garante que apenas uma instância deste workflow seja executada por vez.
# O grupo estático garante que NENHUMA operação de terraform (plan, apply, destroy)
# rode em paralelo, independentemente da branch ou do workflow.
concurrency:
  group: terraform-state-lock
  cancel-in-progress: true

jobs:
  terraform:
    name: 'Terraform Plan/Apply'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform # Indica que os comandos devem rodar na pasta terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::239409137076:role/role-eks-fiap
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request')
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request')
        run: terraform apply -auto-approve -input=false tfplan

  update-pr-status:
    name: 'Update PR Status'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [terraform]

    steps:
      - name: Update PR status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Terraform Deploy'
          state: ${{ needs.terraform.result }}
          sha: ${{ github.event.pull_request.head.sha }}