name: 'Terraform PR Automation'

on:
  push:
    branches:
      - 'feature/**'

jobs:
  validate_and_create_pr:
    name: 'Validate Terraform and Create PR'
    runs-on: ubuntu-latest

    # Permissões necessárias para o workflow
    permissions:
      contents: write      # Para fazer checkout do código
      pull-requests: write # Para criar o Pull Request

    steps:
      # 1. Faz o checkout do código da sua branch
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Busca todo o histórico para garantir que as alterações sejam detectadas

      # 2. Configura o ambiente Terraform
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          # Opcional: Especifique a versão do Terraform que você usa
          terraform_version: 1.5.0

      # 3. Verifica a formatação do código Terraform
      # O '-check' faz o passo falhar se o código não estiver formatado
      - name: 'Terraform Format Check'
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

      # 4. Inicializa o Terraform para baixar providers
      - name: 'Terraform Init'
        id: init
        run: terraform init

      # 5. Valida a sintaxe do código Terraform
      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

      # 6. Gera um plano de execução para garantir que não há erros
      # -input=false é crucial para automação
      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -input=false -no-color

      # 7. Cria o Pull Request se todos os passos anteriores tiveram sucesso
      - name: 'Create Pull Request'
        uses: peter-evans/create-pull-request@v6
        with:
          # O GITHUB_TOKEN é gerado automaticamente pelo GitHub Actions
          token: ${{ secrets.GITHUB_TOKEN }}
          # Título do Pull Request usando o nome da branch
          title: 'Feature: ${{ github.ref_name }}'
          # Corpo do Pull Request
          body: |
            Pull request automático da branch `${{ github.ref_name }}`.

            O workflow de CI validou o código Terraform com sucesso:
            - `terraform fmt -check`
            - `terraform init`
            - `terraform validate`
            - `terraform plan`

            Por favor, revise as mudanças antes de fazer o merge.
          # A branch que acionou o workflow (ex: feature/nova-infra)
          branch: ${{ github.ref_name }}
          # A branch alvo do Pull Request
          base: main
          # Adiciona uma label ao PR para fácil identificação
          labels: terraform, automated pr
          # Opcional: Atribui o PR à pessoa que fez o commit
          assignees: ${{ github.actor }}