name: 'Deploy to Main'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-state-lock
  cancel-in-progress: false

jobs:
  terraform-eks:
    name: 'Deploy EKS Cluster'
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.get_cluster_name.outputs.cluster_name }}
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Init & Apply EKS
        id: apply
        run:  terraform apply -target=module.eks -auto-approve

      - name: Get cluster name
        id: get_cluster_name
        run: echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT

        # --- JOB 2: Instala os addons ---
  terraform-addons:
    name: 'Deploy Addons'
    needs: terraform-eks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ needs.terraform-eks.outputs.cluster_name }}
          
      - name: Terraform Init & Apply Addons
        run: |
          terraform init
          terraform apply -target=helm_release.nginx_ingress_controller -auto-approve
